Lora locations
AGI-Collective/multimodal pull request #45
Opened 2023-08-18 13:57 UTC by daniel-z-kaplan

@kshitijkg

2023-08-18 13:58 UTC, daniel-z-kaplan commented
The only files modified are megatron/training.py, and megatron/models/adapter.py

2023-09-13 12:54 UTC, kshitijkg requested changes

2023-09-13 12:54 UTC, kshitijkg commented on megatron/model/adapter.py
> +        self.output.bias.data = torch.clamp(self.output_lora.bias.data, min=-2 * std, max=2 * std)
This should be self.output_lora?

2023-09-13 12:54 UTC, kshitijkg commented on megatron/model/adapter.py
> +        hidden_states = self.adapt(attn_output) + attn_output
Not the same as whats done in parallel version?

2023-09-13 12:54 UTC, kshitijkg commented on megatron/model/adapter.py
> +        hidden_states = attn_output + (self.adapt(x) * self.adapter_scale)
- Not the same as whats done in non parallel version?
- This results in:
result = (1+scale)attn_output + scaleadapter_branch(attn_output)

Doesnt look like that should be the case?

2023-09-13 12:54 UTC, kshitijkg commented on megatron/model/adapter.py
> +            lin = Adapter(dim = child.out_features, is_lora = True)#We just assume it's same input and output
Linear Weights are not being copied over

2023-09-13 12:54 UTC, kshitijkg commented on megatron/model/adapter.py
> +        result += x @ self.downsample_adapter_lora.T @ self.upsample_adapter_lora.T * self.scaling
Avoid using inplace operations in Torch. Not a big issue here since original result is anyways frozen, but better to avoid this.

2023-09-22 14:08 UTC, closed without merging